### ISSUE TITLE
cmd different than the repo name

### ISSUE THREAD

**Issue by ivucica** [emersion/emuarius#5]
Just wondering -- is the mismatch intentional?

Observe: github.com/emersion/<b>emuarius</b>/cmd/<b>emarius</b>

The former also appears in config file name. The latter... does not. :)

**Comment by freemountain** [comment]
@emersion this was also fixed with PR [#6](https://github.com/emersion/emuarius/pull/6)

**Comment by emersion** [comment]
Right, thanks!
